package model;
// Generated 26/03/2022 08:12:38 AM by Hibernate Tools 5.3.0.Beta2

import java.time.LocalDate;
import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * SgdConvenio generated by hbm2java
 */

@Entity
@Table(name = "sgd_convenio", schema = "dbo")
public class SgdConvenio implements java.io.Serializable {

	private Integer convId;
	private int convNumero;
	private int convYear;
	private LocalDate convFechaInicio;
	private LocalDate convFechaFin;
	private String convEstado;
	private String convPath;
	private int comaId;
	private float convValor;
	private String convApodo;
	private int usuId;

	public int getUsuId() {
		return usuId;
	}

	public void setUsuId(int usuId) {
		this.usuId = usuId;
	}

	public String getConvApodo() {
		return convApodo;
	}

	public void setConvApodo(String convApodo) {
		this.convApodo = convApodo;
	}

	public float getConvValor() {
		return convValor;
	}

	public void setConvValor(float convValor) {
		this.convValor = convValor;
	}

	public SgdConvenio() {
	}

	public SgdConvenio(int convNumero, String convEstado, int comaId) {
		this.convNumero = convNumero;
		this.convEstado = convEstado;
		this.comaId = comaId;
	}

	public SgdConvenio(int convNumero, int convYear, LocalDate convFechaInicio, LocalDate convFechaFin,
			String convEstado, String convPath, int comaId, float convValor) {
		this.convNumero = convNumero;
		this.convYear = convYear;
		this.convFechaInicio = convFechaInicio;
		this.convFechaFin = convFechaFin;
		this.convEstado = convEstado;
		this.convPath = convPath;
		this.comaId = comaId;
		this.convValor = convValor;
	}

	public Integer getConvId() {
		return this.convId;
	}

	public void setConvId(Integer convId) {
		this.convId = convId;
	}

	public int getConvNumero() {
		return this.convNumero;
	}

	public void setConvNumero(int convNumero) {
		this.convNumero = convNumero;
	}

	public int getConvYear() {
		return this.convYear;
	}

	public void setConvYear(int convYear) {
		this.convYear = convYear;
	}

	public LocalDate getConvFechaInicio() {
		return this.convFechaInicio;
	}

	public void setConvFechaInicio(LocalDate date) {
		this.convFechaInicio = date;
	}

	public LocalDate getConvFechaFin() {
		return this.convFechaFin;
	}

	public void setConvFechaFin(LocalDate fechaFinJs) {
		this.convFechaFin = fechaFinJs;
	}

	public String getConvEstado() {
		return this.convEstado;
	}

	public void setConvEstado(String convEstado) {
		this.convEstado = convEstado;
	}

	public String getConvPath() {
		return convPath;
	}

	public void setConvPath(String convPath) {
		this.convPath = convPath;
	}
	
	public int getComaId() {
		return this.comaId;
	}

	public void setComaId(int comaId) {
		this.comaId = comaId;
	}

}
