package model;
// Generated 26/03/2022 08:12:38 AM by Hibernate Tools 5.3.0.Beta2

import java.io.Serializable;

/**
 * SgdDepartamento generated by hbm2java
 */
public class SgdDepartamento implements java.io.Serializable {

	private Integer depaId;
	private Serializable depaNombre;
	private Serializable depaCodDane;

	public SgdDepartamento() {
	}

	public SgdDepartamento(Serializable depaNombre, Serializable depaCodDane) {
		this.depaNombre = depaNombre;
		this.depaCodDane = depaCodDane;
	}

	public Integer getDepaId() {
		return this.depaId;
	}

	public void setDepaId(Integer depaId) {
		this.depaId = depaId;
	}

	public Serializable getDepaNombre() {
		return this.depaNombre;
	}

	public void setDepaNombre(Serializable depaNombre) {
		this.depaNombre = depaNombre;
	}

	public Serializable getDepaCodDane() {
		return this.depaCodDane;
	}

	public void setDepaCodDane(Serializable depaCodDane) {
		this.depaCodDane = depaCodDane;
	}

}
