package model;
// Generated 26/03/2022 08:12:38 AM by Hibernate Tools 5.3.0.Beta2

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SgdEntidad generated by hbm2java
 */
@Entity
@Table(name = "sgd_entidad", schema = "dbo")
public class SgdEntidad implements java.io.Serializable {

	private int entiId;
	private String entiNombre;
	private String entiTipoIdentificacion;
	private int tiidId;
	private String entiDireccion;
	private String entiTelefono;
	private int muniId;
	private String entIesId;

	public SgdEntidad() {
	}

	public SgdEntidad(int entiId, String entiNombre, String entiTipoIdentificacion, int tiidId,
			int muniId) {
		this.entiId = entiId;
		this.entiNombre = entiNombre;
		this.entiTipoIdentificacion = entiTipoIdentificacion;
		this.tiidId = tiidId;
		this.muniId = muniId;
	}

	public SgdEntidad(int entiId, String entiNombre, String entiTipoIdentificacion, int tiidId,
			String entiDireccion, String entiTelefono, int muniId, String entIesId) {
		this.entiId = entiId;
		this.entiNombre = entiNombre;
		this.entiTipoIdentificacion = entiTipoIdentificacion;
		this.tiidId = tiidId;
		this.entiDireccion = entiDireccion;
		this.entiTelefono = entiTelefono;
		this.muniId = muniId;
		this.entIesId = entIesId;
	}

	@Id
	@Column(name = "ent_id", unique = true, nullable = false)
	public int getEntiId() {
		return this.entiId;
	}

	public void setEntiId(int entiId) {
		this.entiId = entiId;
	}

	public Serializable getEntiNombre() {
		return this.entiNombre;
	}

	public void setEntiNombre(String entiNombre) {
		this.entiNombre = entiNombre;
	}

	public Serializable getEntiTipoIdentificacion() {
		return this.entiTipoIdentificacion;
	}

	public void setEntiTipoIdentificacion(String entiTipoIdentificacion) {
		this.entiTipoIdentificacion = entiTipoIdentificacion;
	}

	public int getTiidId() {
		return this.tiidId;
	}

	public void setTiidId(int tiidId) {
		this.tiidId = tiidId;
	}

	public Serializable getEntiDireccion() {
		return this.entiDireccion;
	}

	public void setEntiDireccion(String entiDireccion) {
		this.entiDireccion = entiDireccion;
	}

	public Serializable getEntiTelefono() {
		return this.entiTelefono;
	}

	public void setEntiTelefono(String entiTelefono) {
		this.entiTelefono = entiTelefono;
	}

	public int getMuniId() {
		return this.muniId;
	}

	public void setMuniId(int muniId) {
		this.muniId = muniId;
	}

	public Serializable getEntIesId() {
		return this.entIesId;
	}

	public void setEntIesId(String entIesId) {
		this.entIesId = entIesId;
	}

}
