package model;
// Generated 26/03/2022 08:12:38 AM by Hibernate Tools 5.3.0.Beta2

import java.io.Serializable;
import java.util.Date;

/**
 * SgdPersona generated by hbm2java
 */
public class SgdPersona implements java.io.Serializable {

	private Integer persId;
	private Serializable persNombre;
	private Serializable persApellido;
	private int tiidId;
	private Serializable persIdentificacion;
	private Date persFechaNacimiento;
	private Integer muniId;
	private Serializable persEstrato;
	private Serializable persGenero;
	private Serializable persGrupoPoblacional;
	private Serializable persCalificaSisben;
	private Serializable persEstado;

	public SgdPersona() {
	}

	public SgdPersona(Serializable persNombre, int tiidId, Serializable persIdentificacion, Serializable persEstado) {
		this.persNombre = persNombre;
		this.tiidId = tiidId;
		this.persIdentificacion = persIdentificacion;
		this.persEstado = persEstado;
	}

	public SgdPersona(Serializable persNombre, Serializable persApellido, int tiidId, Serializable persIdentificacion,
			Date persFechaNacimiento, Integer muniId, Serializable persEstrato, Serializable persGenero,
			Serializable persGrupoPoblacional, Serializable persCalificaSisben, Serializable persEstado) {
		this.persNombre = persNombre;
		this.persApellido = persApellido;
		this.tiidId = tiidId;
		this.persIdentificacion = persIdentificacion;
		this.persFechaNacimiento = persFechaNacimiento;
		this.muniId = muniId;
		this.persEstrato = persEstrato;
		this.persGenero = persGenero;
		this.persGrupoPoblacional = persGrupoPoblacional;
		this.persCalificaSisben = persCalificaSisben;
		this.persEstado = persEstado;
	}

	public Integer getPersId() {
		return this.persId;
	}

	public void setPersId(Integer persId) {
		this.persId = persId;
	}

	public Serializable getPersNombre() {
		return this.persNombre;
	}

	public void setPersNombre(Serializable persNombre) {
		this.persNombre = persNombre;
	}

	public Serializable getPersApellido() {
		return this.persApellido;
	}

	public void setPersApellido(Serializable persApellido) {
		this.persApellido = persApellido;
	}

	public int getTiidId() {
		return this.tiidId;
	}

	public void setTiidId(int tiidId) {
		this.tiidId = tiidId;
	}

	public Serializable getPersIdentificacion() {
		return this.persIdentificacion;
	}

	public void setPersIdentificacion(Serializable persIdentificacion) {
		this.persIdentificacion = persIdentificacion;
	}

	public Date getPersFechaNacimiento() {
		return this.persFechaNacimiento;
	}

	public void setPersFechaNacimiento(Date persFechaNacimiento) {
		this.persFechaNacimiento = persFechaNacimiento;
	}

	public Integer getMuniId() {
		return this.muniId;
	}

	public void setMuniId(Integer muniId) {
		this.muniId = muniId;
	}

	public Serializable getPersEstrato() {
		return this.persEstrato;
	}

	public void setPersEstrato(Serializable persEstrato) {
		this.persEstrato = persEstrato;
	}

	public Serializable getPersGenero() {
		return this.persGenero;
	}

	public void setPersGenero(Serializable persGenero) {
		this.persGenero = persGenero;
	}

	public Serializable getPersGrupoPoblacional() {
		return this.persGrupoPoblacional;
	}

	public void setPersGrupoPoblacional(Serializable persGrupoPoblacional) {
		this.persGrupoPoblacional = persGrupoPoblacional;
	}

	public Serializable getPersCalificaSisben() {
		return this.persCalificaSisben;
	}

	public void setPersCalificaSisben(Serializable persCalificaSisben) {
		this.persCalificaSisben = persCalificaSisben;
	}

	public Serializable getPersEstado() {
		return this.persEstado;
	}

	public void setPersEstado(Serializable persEstado) {
		this.persEstado = persEstado;
	}

}
