package model;
// Generated 26/03/2022 08:12:38 AM by Hibernate Tools 5.3.0.Beta2

import java.io.Serializable;

/**
 * SgdTipoIdentificacion generated by hbm2java
 */
public class SgdTipoIdentificacion implements java.io.Serializable {

	private Integer tiidId;
	private Serializable tiidDescripcion;
	private String tiidEstado;

	public SgdTipoIdentificacion() {
	}

	public SgdTipoIdentificacion(Serializable tiidDescripcion, String tiidEstado) {
		this.tiidDescripcion = tiidDescripcion;
		this.tiidEstado = tiidEstado;
	}

	public Integer getTiidId() {
		return this.tiidId;
	}

	public void setTiidId(Integer tiidId) {
		this.tiidId = tiidId;
	}

	public Serializable getTiidDescripcion() {
		return this.tiidDescripcion;
	}

	public void setTiidDescripcion(Serializable tiidDescripcion) {
		this.tiidDescripcion = tiidDescripcion;
	}

	public String getTiidEstado() {
		return this.tiidEstado;
	}

	public void setTiidEstado(String tiidEstado) {
		this.tiidEstado = tiidEstado;
	}

}
