package model;
// Generated 26/03/2022 08:12:38 AM by Hibernate Tools 5.3.0.Beta2

import java.io.Serializable;

/**
 * SgdTipoRubro generated by hbm2java
 */
public class SgdTipoRubro implements java.io.Serializable {

	private Integer tiruId;
	private Serializable tiruNombre;
	private Serializable tiruEstado;

	public SgdTipoRubro() {
	}

	public SgdTipoRubro(Serializable tiruNombre, Serializable tiruEstado) {
		this.tiruNombre = tiruNombre;
		this.tiruEstado = tiruEstado;
	}

	public Integer getTiruId() {
		return this.tiruId;
	}

	public void setTiruId(Integer tiruId) {
		this.tiruId = tiruId;
	}

	public Serializable getTiruNombre() {
		return this.tiruNombre;
	}

	public void setTiruNombre(Serializable tiruNombre) {
		this.tiruNombre = tiruNombre;
	}

	public Serializable getTiruEstado() {
		return this.tiruEstado;
	}

	public void setTiruEstado(Serializable tiruEstado) {
		this.tiruEstado = tiruEstado;
	}

}
